# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "private_network", ip: "10.2.0.10", netmask: "255.255.0.0"
    #config.vm.network "public_network"
    config.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024", "--nicpromisc2", "allow-all"]
    end

    config.vm.provision "docker" do |d|
        #d.build_image "/vagrant"
    end

    config.vm.synced_folder "/Users/maartenhuijsmans", "/Users/maartenhuijsmans",
        :nfs => true,
        :linux__nfs_options => ["no_root_squash"], :map_uid => 0, :map_gid => 0

    config.vm.provision "shell", inline: <<SCRIPT
        echo 'cd /vagrant' >> /home/vagrant/.profile
        sudo apt-get install qemu binfmt-support qemu-user-static -y
        #sudo sh -c 'echo ":arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:" >/proc/sys/fs/binfmt_misc/register'

        usermod -a -G docker vagrant
        echo 'DOCKER_OPTS="-g=/mnt/docker -H 0.0.0.0:4243"' >> /etc/default/docker
        # DOCKER_OPTS="-g=/mnt/docker -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock"

        echo '# Set DOCKER_HOST' >> /home/vagrant/.bashrc
        echo 'export DOCKER_HOST="tcp://127.0.0.1:4243"' >> /home/vagrant/.bashrc
        service docker restart
SCRIPT

end
